# Generated by Django 4.2.6 on 2023-10-27 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_remove_project_start_time_check_comment_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported_by',
            field=models.ManyToManyField(related_name='reported_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
