# Generated by Django 4.2.6 on 2023-10-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_start_time_check_project_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
