# Generated by Django 4.2.6 on 2023-10-27 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_merge_20231027_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250000)]),
        ),
    ]
