# Generated by Django 4.2.6 on 2023-10-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_start_time_check_and_more'),
        ('projects', '0013_alter_project_total_target'),
    ]

    operations = [
    ]
