# Generated by Django 4.2.6 on 2023-10-29 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reported_by',
            field=models.ManyToManyField(related_name='reported_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
