# Generated by Django 4.2.6 on 2023-10-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_project_start_time_check_and_more'),
        ('projects', '0020_alter_comment_parent'),
    ]

    operations = [
    ]
